### ISSUE TITLE
libavcodec build errors

### ISSUE THREAD

**Issue by Muriukidavid** [jaswdr/guvcview#8]
I tried to build in _**Ubuntu 24.04.3 LTS**_ but I am having issues with the libavcodec for both uvc_h264.c and video_codecs.c. There are missing definitions and functions, some have been renamed and others are just not there anymore.

### missing declarations
CODEC_FLAG_4MV -> AV_CODEC_FLAG_4MV
CODEC_FLAG2_FAST -> AV_CODEC_FLAG2_FAST
ME_EPZS
ME_HEX

### missing functions
uvc_h264.c:1008:9: warning: implicit declaration of function 'avcodec_register_all'
uvc_h264.c:1110:19: warning: implicit declaration of function 'avcodec_decode_video2'
jpeg_decoder.c:1530:19: warning: implicit declaration of function 'avcodec_decode_video2'

<img width="1223" height="332" alt="Image" src="https://github.com/user-attachments/assets/55b2dadb-8402-4509-a57b-c75962910959" />

Which version of libavcodec-dev should I build against to avoid this errors?

> dpkg -l "*avcodec*" | grep ii
> ii  libavcodec-dev:amd64     7:6.1.1-3ubuntu5 amd64        FFmpeg library with de/encoders for audio/video codecs - development files
